(define (domain sokoban-domain)
  (:requirements :equality)
  (:predicates (player_at ?x) (box_at ?x) (adj ?x ?y) (pushable ?x ?y))
  (:action move-player
           :parameters (?spos ?epos)
           :precondition (and (player_at ?spos)
                              (not (box_at ?epos))
			      (adj ?spos ?epos))
           :effect (and (player_at ?epos)
                        (not (player_at ?spos))))
  (:action push-box
	   :parameters (?ppos ?bpos ?dpos)
	   :precondition (and (player_at ?ppos)
			      (box_at ?bpos)
			      (not (box_at ?dpos))
			      (adj ?ppos ?bpos)
			      (adj ?bpos ?dpos)
			      (pushable ?ppos ?dpos))
	   :effect (and (player_at ?bpos)
			(not (player_at ?ppos))
			(box_at ?dpos)
			(not (box_at ?bpos))))
)
